### PR TITLE
Implementation of Arduino smartcar connection to MQTT broker. Re-entry.

### PR DESCRIPTION
**Pull request by d0nate110**
First draft implementation of the Arduino smartcar's connection to the MQTT broker. So far It receives publishing commands from the terminal, and is able to publish front distance sensor data back to the terminal. 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by Akuien — APPROVED** [review]

**Comment by Akuien** [comment]
Nice, work.

**Comment by d0nate110** [comment]
All checks pass. The acceptance criteria for user story is partially satisfied, because we need to implement Android side of the MQTT connectivity to the broker.

**Comment by platisd** [comment]
> All checks pass. The acceptance criteria for user story is partially satisfied, because we need to implement Android side of the MQTT connectivity to the broker.

Then why did you close #27 ? :thinking:

**Comment by d0nate110** [comment]
The github automation algorithm closed it automatically, we are going to reopen it now :)

**Pull request merged**
