### PR TITLE
Create google-services.json

### PR DESCRIPTION
**Pull request by nazlimoghaddam**
### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by platisd** [comment]
The file is still visible and exposed :sweat:

**Comment by platisd** [comment]
The only way to get rid of this pull request is to contact GitHub and tell them to delete it. Also, it should have beeen google-service**s**.json

**Comment by platisd** [comment]
OK, I actually may have gotten rid of it now

**Comment by Akuien** [comment]
So we can finally delete both the branch and the request?

**Comment by platisd** [comment]
No need to take any further action, the sensitive/secret information has been removed from the history now.

**Pull request closed without merging**
